pid-file: /run/raketman-daemon # пусть к pid файлу
lock-by-pid: false # блокировка по пиду, есди не используется timer
max-execution-time: 640000  # время выполнение, после которого он завершает работу
sleep: 100 # время в микросекундах, которое тратиться на прерывания скрипта,чтобы не нагружать процессор
